# Generated by Django 4.1.5 on 2023-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0002_resumen_resumen_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diag_disease',
            field=models.CharField(choices=[('RETINOPATIA', 'Retinopatia'), ('GLAUCOMA', 'Glaucoma'), ('CATARATAS', 'cataratas')], max_length=25, verbose_name='Tipo de Enfermedad'),
        ),
    ]
