# Generated by Django 4.1.5 on 2023-01-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0003_alter_diagnostico_diag_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disase',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_nom', models.CharField(max_length=25, verbose_name='Nombre de Enfermedad')),
                ('dis_desc', models.CharField(max_length=150, verbose_name='Descripcion de Enfermedad')),
                ('dis_fecha_cre', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('dis_fecha_mod', models.DateTimeField(null=True, verbose_name='Fecha de modificacion')),
                ('dis_est', models.BooleanField(default=True, verbose_name='Estado de la Enfermedad')),
            ],
            options={
                'db_table': 'tbl_disase',
            },
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='dis_id',
            field=models.ForeignKey(db_column='dis_id', default=1, on_delete=django.db.models.deletion.RESTRICT, to='api5.disase'),
        ),
    ]
