# Generated by Django 4.1.5 on 2023-01-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0004_disase_diagnostico_dis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='diag_rnroDoc',
            field=models.CharField(blank='', default='', max_length=15, verbose_name='Nro documento'),
        ),
    ]
