# Generated by Django 4.1.5 on 2023-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0005_diagnostico_diag_rnrodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diag_rnroDoc',
            field=models.CharField(default='', max_length=15, verbose_name='Nro documento'),
        ),
    ]
