# Generated by Django 4.1.5 on 2023-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0006_alter_diagnostico_diag_rnrodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diag_rnroDoc',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Nro documento'),
        ),
    ]
