# Generated by Django 4.1.5 on 2023-01-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0008_resumen_est_disase_alter_resumen_est_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
