# Generated by Django 4.1.5 on 2023-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0009_resumen_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa_log',
            field=models.ImageField(blank='', default='', upload_to='retinopatia/logo'),
        ),
    ]
