# Generated by Django 4.1.5 on 2023-02-23 03:16

import api5.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0010_empresa_empresa_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diag_img_eye_left',
            field=models.ImageField(blank='', default='', upload_to=api5.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='diag_img_eye_right',
            field=models.ImageField(blank='', default='', upload_to=api5.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_log',
            field=models.ImageField(blank='', default='', upload_to=api5.models.logo_file_path),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CARNET', 'Carnet de Extranjeria'), ('LIBRETA', 'Libreta Electoral'), ('COD_SIST', 'codigo de Sistema')], max_length=25, verbose_name='Tipo Documento'),
        ),
    ]
